"""empty message

Revision ID: 0e84d37490ef
Revises: 2c57890aaffc
Create Date: 2019-01-20 20:12:05.871206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e84d37490ef'
down_revision = '2c57890aaffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('measure', sa.CHAR(length=255), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'measure', schema='app')
    # ### end Alembic commands ###
