"""empty message

Revision ID: 17f0f2e0b7a0
Revises: 8f0dbc7cc2fb
Create Date: 2019-03-01 15:43:30.099920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f0f2e0b7a0'
down_revision = '8f0dbc7cc2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('name1', sa.String(length=255), nullable=True), schema='app')
    op.drop_column('office', 'name', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office', sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=True), schema='app')
    op.drop_column('office', 'name1', schema='app')
    # ### end Alembic commands ###
