"""empty message

Revision ID: 2c57890aaffc
Revises: 889c89bede28
Create Date: 2019-01-20 20:11:29.302480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c57890aaffc'
down_revision = '889c89bede28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'measure', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('measure', sa.INTEGER(), autoincrement=False, nullable=True), schema='app')
    # ### end Alembic commands ###
