"""empty message

Revision ID: 37471f553d52
Revises: 0e84d37490ef
Create Date: 2019-01-20 20:13:17.977170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37471f553d52'
down_revision = '0e84d37490ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='app')
    # ### end Alembic commands ###
