"""empty message

Revision ID: 54963829a3c6
Revises: 01418a0bdd97
Create Date: 2019-03-05 00:45:13.803814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54963829a3c6'
down_revision = '01418a0bdd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prod_section', sa.Column('name1', sa.String(length=255), nullable=True), schema='app')
    op.drop_column('prod_section', 'name', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prod_section', sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=True), schema='app')
    op.drop_column('prod_section', 'name1', schema='app')
    # ### end Alembic commands ###
