"""empty message

Revision ID: 5b5ddb5b4208
Revises: 742dee560465
Create Date: 2019-02-10 13:50:45.538046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5ddb5b4208'
down_revision = '742dee560465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.String(length=255), nullable=True), schema='app')
    op.drop_column('product', 'name1', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name1', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='app')
    op.drop_column('product', 'name', schema='app')
    # ### end Alembic commands ###
