"""empty message

Revision ID: 889c89bede28
Revises: 9d9c6df383d6
Create Date: 2019-01-20 19:53:54.868971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889c89bede28'
down_revision = '9d9c6df383d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'test', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True), schema='app')
    # ### end Alembic commands ###
