"""empty message

Revision ID: 96136e61317f
Revises: f4cbf1f2e3d1
Create Date: 2019-01-19 19:33:56.675178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96136e61317f'
down_revision = 'f4cbf1f2e3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('office_test', sa.Integer(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'office_test', schema='app')
    # ### end Alembic commands ###
