"""empty message

Revision ID: 9d9c6df383d6
Revises: ea0f8c7c6261
Create Date: 2019-01-19 21:26:33.469112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d9c6df383d6'
down_revision = 'ea0f8c7c6261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.CHAR(length=255), nullable=True),
    sa.Column('code', sa.CHAR(length=255), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('image', sa.CHAR(length=255), nullable=True),
    sa.Column('measure', sa.Integer(), nullable=True),
    sa.Column('ball', sa.Integer(), nullable=True),
    sa.Column('nds', sa.Integer(), nullable=True),
    sa.Column('sale', sa.CHAR(length=1), nullable=True),
    sa.Column('cat', sa.Integer(), nullable=True),
    sa.Column('office', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('sect', sa.Integer(), nullable=True),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modif', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.drop_table('item', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('app.item_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.CHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('code', sa.CHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', sa.CHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('measure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('cat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('office', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sect', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modif', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='item_pkey'),
    schema='app'
    )
    op.drop_table('product', schema='app')
    # ### end Alembic commands ###
