"""empty message

Revision ID: ade58ef0ee10
Revises: 5b5ddb5b4208
Create Date: 2019-02-10 13:51:29.278842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade58ef0ee10'
down_revision = '5b5ddb5b4208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('code1', sa.String(length=255), nullable=True), schema='app')
    op.drop_column('product', 'code', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('code', sa.CHAR(length=255), autoincrement=False, nullable=True), schema='app')
    op.drop_column('product', 'code1', schema='app')
    # ### end Alembic commands ###
