"""empty message

Revision ID: d5c58f100c61
Revises: 54963829a3c6
Create Date: 2019-03-05 00:45:56.546419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c58f100c61'
down_revision = '54963829a3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prod_section', sa.Column('name', sa.String(length=255), nullable=True), schema='app')
    op.drop_column('prod_section', 'name1', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prod_section', sa.Column('name1', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='app')
    op.drop_column('prod_section', 'name', schema='app')
    # ### end Alembic commands ###
