"""empty message

Revision ID: daf2e145df05
Revises: 08bb36c78a11
Create Date: 2019-02-17 00:42:03.031274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf2e145df05'
down_revision = '08bb36c78a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prod_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.add_column('prod_cat', sa.Column('desc', sa.Text(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prod_cat', 'desc', schema='app')
    op.drop_table('prod_component', schema='app')
    # ### end Alembic commands ###
