"""empty message

Revision ID: ea0f8c7c6261
Revises: 96136e61317f
Create Date: 2019-01-19 19:34:39.727477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0f8c7c6261'
down_revision = '96136e61317f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'office_test', schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('office_test', sa.INTEGER(), autoincrement=False, nullable=True), schema='app')
    # ### end Alembic commands ###
