"""empty message

Revision ID: f4cbf1f2e3d1
Revises: 
Create Date: 2019-01-19 19:33:05.543898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cbf1f2e3d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.CHAR(length=255), nullable=True),
    sa.Column('code', sa.CHAR(length=255), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('image', sa.CHAR(length=255), nullable=True),
    sa.Column('measure', sa.Integer(), nullable=True),
    sa.Column('ball', sa.Integer(), nullable=True),
    sa.Column('nds', sa.Integer(), nullable=True),
    sa.Column('sale', sa.CHAR(length=1), nullable=True),
    sa.Column('cat', sa.Integer(), nullable=True),
    sa.Column('office', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('sect', sa.Integer(), nullable=True),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modif', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item', schema='app')
    # ### end Alembic commands ###
